apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-fastapi
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:  
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:  
      containers:
        - name: fastapi
          image: {{ .Values.fastapi.image }}
          ports:
            - containerPort: {{ .Values.fastapi.service.port }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-phpmyadmin
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:  
  replicas: {{ .Values.phpmyadmin.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:  
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.phpmyadmin.image }}
          ports:
            - containerPort: {{ .Values.phpmyadmin.service.port }}
