apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-fastapi
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.fastapi.service.type }}
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: {{ .Values.fastapi.service.port }}
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app: fastapi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-phpmyadmin
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.phpmyadmin.service.type }}
  ports:
    - port: {{ .Values.phpmyadmin.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app: phpmyadmin
