apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql
 namespace : {{ .Values.namespace }}
spec:
 selector:
   matchLabels:
     {{- include "helm.selectorLabels" . | nindent 6 }}
 replicas: {{ .Values.mysql.replicaCount }}
 template:
   metadata:
     labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
   spec:
     containers:
     - name: mysql
       image: {{ .Values.mysql.image }}
       ports:
       - containerPort: {{ .Values.mysql.service.port }}
       volumeMounts:
       - name: {{ .Values.pvc.name }}
         mountPath: /var/lib/mysql
       env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: mysql
             key: mysql-root-password
       - name: MYSQL_DATABASE
         value : "storedb"
     volumes:
      - name: {{ .Values.pvc.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}