apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace : standard
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
