apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql
 namespace: standard
spec:
 selector:
   matchLabels:
     app: mysql
 serviceName: mysql
 replicas: 1
 template:
   metadata:
     labels:
       app: mysql
   spec:
     containers:
     - name: mysql
       image: mysql:8
       ports:
       - containerPort: 3306
         name: mysql
       env:
       - name: MYSQL_ROOT_PASSWORD
         value: "password"
       - name: MYSQL_DATABASE
         value: "storedb"
