namespace: helm

mysql:
 image: mysql:8
 replicaCount: 1
 service:
  type: ClusterIP
  port: 3306

pvc:
  name : mysql-data
  accessMode: ReadWriteOnce
  storage: 10Gi
  storageClassName: local-path

phpmyadmin:
 image: phpmyadmin
 replicaCount: 1
 service:
  type: ClusterIP
  port: 8080
  

fastapi:
 image: camillebre/fastapi
 replicaCount: 3 
 service:
  type: ClusterIP
  port: 80 
 ingress:
  enabled: true
  hostname: k8.lapinson.cloudns.ph

hpa:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
