namespace: helm

mysql:
 image: mysql:8
 replicaCount: 1
 service:
  type: ClusterIP
  port: 3306
 password: "password"
 database: "storedb"
    #    pvc:
    #    accessMode: ReadWriteMany
    #    storage: 10Gi
    #    storageClassName: local-path

phpmyadmin:
 image: phpmyadmin
 replicaCount: 1
 service:
  type: ClusterIP
  port: 80

fastapi:
 image: camillebre/fastapi
 replicaCount: 3 
 service:
  type: LoadBalancer
  port: 80 
 ingress:
  enabled: true
  hostname: k8.lapinson.cloudns.ph
